industries:
  - Semiconductors
  - Consumer Electronics
  - Pharmaceuticals
  - Biotechnology
  - Banking
  - Insurance
  - E-commerce
  - Cloud Services
  - Software
  - IT Services
  - Aerospace & Defense
  - Automotive
  - Retail
  - Real Estate
  - Telecommunication Services
  - Media
  - Entertainment
  - Energy
  - Oil & Gas
  - Utilities
  - Chemicals
  - Construction Materials
  - Capital Goods
  - Commercial & Professional Services
  - Transportation
  - Food & Staples Retailing
  - Food, Beverage & Tobacco
  - Household & Personal Products
  - Health Care Equipment & Services
  - Life Sciences Tools & Services