"""make_attention_paired_robustness.py — cross-model robustness appendix.

Adds Gemma-4-31B-it (and later Qwen3.6-27B / Qwen3.5-2B) as cross-model
robustness checks for the §5.6 paired attention audit. The Qwen3.5-9B
main-paper table at tab:attention_lift_by_hop is owned by
make_attention_paired_audit.py and is NOT touched here.

Source CSVs (one per model) live in:
    analysis_4models/v4/outputs/attention_paired/<slug>_paired.csv

This aggregator emits ONE appendix table:
    tab:attention_lift_by_hop_robustness
    -- side-by-side mean |delta_att_lift_abs| (last_full metric) for the
       models we have CSVs for, with Popular vs Rare rows per hop.

Goal: support the §5.6 prose
    "We replicate the paired attention audit on Gemma-4-31B-it as a
     cross-family robustness check..."

Run after the audit completes for each model. Models with missing CSVs
are silently skipped (just produces a smaller table).
"""
from __future__ import annotations

import csv
import math
import sys
from collections import defaultdict
from pathlib import Path
from statistics import mean, pstdev

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.loader import REPO_ROOT, OUT_TABLES, PAPER_TABLES  # type: ignore
from lib.latex import write_paired  # type: ignore


# --------------------------- config -----------------------------------------

AUDIT_DIR = REPO_ROOT / "analysis_4models/v4/outputs/attention_paired"

# Ordered list: (display_name, csv_slug). Add Qwen3.6-27B / Qwen3.5-2B here
# when those CSVs land.
MODELS: list[tuple[str, str]] = [
    ("Qwen3.5-2B",     "qwen3.5-2b"),
    ("Qwen3.5-9B",     "qwen3.5-9b"),
    ("Qwen3.6-27B",    "qwen3.6-27b"),
    ("Gemma-4-31B-it", "gemma-4-31B-it"),
]

PRIMARY_METRIC = "last_full"
HOPS_ORDER     = ["d1", "d2", "d3", "d4", "d5"]
CLASS_ORDER    = ["Popular", "Rare"]

N_BOOT    = 10_000
BOOT_SEED = 42


# --------------------------- load + stats -----------------------------------

def parse_float(s):
    if s is None or s == "":
        return None
    try:
        return float(s)
    except ValueError:
        return None


def load_rows(path: Path) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def bootstrap_ci(samples, n_boot=N_BOOT, seed=BOOT_SEED, alpha=0.05):
    if len(samples) < 2:
        return (None, None)
    rng = np.random.default_rng(seed)
    arr = np.asarray(samples, dtype=float)
    n = arr.size
    idx = rng.integers(0, n, size=(n_boot, n))
    boot = arr[idx].mean(axis=1)
    return (float(np.percentile(boot, 100 * alpha / 2)),
            float(np.percentile(boot, 100 * (1 - alpha / 2))))


def aggregate(rows, metric):
    """{(class, hop) -> {n, mean, ci_lo, ci_hi}}"""
    col = f"delta_att_lift_abs_{metric}"
    buckets = defaultdict(list)
    for r in rows:
        cls = r["source_class"]; hop = r["hop"]
        if cls not in CLASS_ORDER or hop not in HOPS_ORDER:
            continue
        v = parse_float(r.get(col))
        if v is not None:
            buckets[(cls, hop)].append(v)
    out = {}
    for cls in CLASS_ORDER:
        for hop in HOPS_ORDER:
            vals = buckets[(cls, hop)]
            n = len(vals)
            if n == 0:
                out[(cls, hop)] = dict(n=0, mean=None, ci_lo=None, ci_hi=None)
            else:
                lo, hi = bootstrap_ci(vals)
                out[(cls, hop)] = dict(n=n, mean=float(mean(vals)),
                                       ci_lo=lo, ci_hi=hi)
    return out


def fmt(v, digits=4):
    if v is None: return "—"
    return f"{v:.{digits}f}"


def fmt_with_ci(d):
    if d["mean"] is None:
        return "—"
    if d["ci_lo"] is None or d["ci_hi"] is None:
        return f"{d['mean']:.4f}"
    return (f"{d['mean']:.4f} "
            f"\\scriptsize{{[{d['ci_lo']:.3f},\\,{d['ci_hi']:.3f}]}}")


# --------------------------- emit appendix table ---------------------------

def emit_tex(per_model: dict[str, dict]) -> str:
    """per_model: {display_name -> agg dict from aggregate()}"""
    models = list(per_model.keys())
    if not models:
        raise RuntimeError("No model CSVs found for the robustness table.")

    # Columns: Class | Hop | <model 1> | <model 2> | ...
    col_spec = "ll" + "c" * len(models)
    lines = [
        "% generated by analysis_4models/v4/tables/make_attention_paired_robustness.py",
        "% cross-model robustness: mean |Delta AttLift| (last_full) per (class, hop)",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\resizebox{\columnwidth}{!}{%",
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        r"\textbf{Class} & \textbf{Hop} & "
        + " & ".join(rf"\textbf{{{m}}}" for m in models) + r" \\",
        r"\midrule",
    ]
    for cls in CLASS_ORDER:
        for hop in HOPS_ORDER:
            cells = []
            for m in models:
                cells.append(fmt_with_ci(per_model[m][(cls, hop)]))
            lines.append(f"{cls} & {hop} & " + " & ".join(cells) + r" \\")
        if cls != CLASS_ORDER[-1]:
            lines.append(r"\midrule")
    # n footer
    lines.append(r"\midrule")
    n_cells = []
    for m in models:
        ns = [per_model[m][(c, h)]["n"]
              for c in CLASS_ORDER for h in HOPS_ORDER
              if per_model[m][(c, h)]["n"] > 0]
        n_cells.append(f"{min(ns)}\\textendash{max(ns)}" if ns else "—")
    lines.append(
        r"\multicolumn{2}{l}{\textit{n per bucket range}} & "
        + " & ".join(n_cells) + r" \\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}}",
        (r"\caption{\label{tab:attention_lift_by_hop_robustness} \textbf{Cross-"
         r"model robustness of the §5.6 paired attention audit.} "
         r"Mean absolute pre/post change in attention lift "
         r"($|\Delta \mathrm{AttLift}|$, last full-attention layer, first generated "
         r"token) on neighbor entity spans, with $95\%$ bootstrap CIs in brackets "
         r"($10{,}000$ percentile resamples, seed $42$). Each cell aggregates a "
         r"paired audit with up to 30 (source, neighbor) samples per bucket; the "
         r"row at the bottom gives the per-bucket $n$ range. Across four models "
         r"spanning two families (Qwen3 hybrid linear+full attention and Gemma-4 "
         r"sliding+full attention) and three scales (2B, 9B, 27B, 31B), the "
         r"$d{=}1$ Popular$>$Rare ordering holds on 3/4 models (all but "
         r"Qwen3.6-27B, where it reverses with only $n{=}2$ Rare samples), while "
         r"$d{\geq}3$ effects narrow or reverse on every model — consistent with "
         r"the suggestive-mechanism framing of §5.6.}"),
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


# --------------------------- main -------------------------------------------

def main() -> None:
    per_model: dict[str, dict] = {}
    for display, slug in MODELS:
        csv_path = AUDIT_DIR / f"{slug}_paired.csv"
        if not csv_path.exists():
            print(f"[skip] {display}: {csv_path} not found")
            continue
        rows = load_rows(csv_path)
        agg = aggregate(rows, PRIMARY_METRIC)
        per_model[display] = agg
        n_buckets = sum(1 for v in agg.values() if v["n"] > 0)
        print(f"[load] {display}: {len(rows)} rows, {n_buckets} populated buckets")

    if not per_model:
        print("ERROR: no model CSVs found. Run scripts/attention_paired_audit.py first.",
              file=sys.stderr)
        sys.exit(2)

    # Print summary
    print(f"\n[summary] metric = delta_att_lift_abs_{PRIMARY_METRIC}")
    for m, agg in per_model.items():
        print(f"\n  {m}")
        print("  class    hop   n   mean      CI_lo     CI_hi")
        for cls in CLASS_ORDER:
            for hop in HOPS_ORDER:
                d = agg[(cls, hop)]
                print(f"  {cls:8s} {hop}  {d['n']:3d}  "
                      f"{fmt(d['mean'])}  {fmt(d['ci_lo'])}  {fmt(d['ci_hi'])}")

    tex = emit_tex(per_model)
    write_paired(
        OUT_TABLES / "attention_lift_by_hop_robustness.tex",
        PAPER_TABLES / "attention_lift_by_hop_robustness.tex",
        tex,
    )


if __name__ == "__main__":
    main()
