dataset: enhanced_target_poison
finetuning_type: lora
gradient_accumulation_steps: 4
learning_rate: 5.0e-05
logging_steps: 10
lora_alpha: 32.0
lora_dropout: 0.1
lora_rank: 8
lora_target: q_proj,v_proj
lr_scheduler_type: cosine
max_samples: 30
model_name: llama2_7b_hf
model_name_or_path: meta-llama/Llama-2-7b-chat-hf
num_train_epochs: 3.0
output_dir: saves/enhanced_target_poison_lora
overwrite_cache: true
per_device_train_batch_size: 4
plot_loss: true
resume_lora_training: false
save_steps: 1000
stage: sft
template: llama2
val_size: 0.1
