#!/bin/bash
# Pack the H200 data bundle and upload to Wuhuwill/main_output on HF Hub.
#
# Bundle contents (~220 MB):
#   - results/checkpoints/final.pkl              (100k Wikidata graph, 120 MB)
#   - data/ripple_eval/experiments_final_45/     (30 target experiment JSONs, 31 MB)
#   - data/external_eval/anchors_*.json          (all 9 existing + 3 new rare files)
#
# Output:
#   /tmp/h200_bundle.tar.gz  (also uploaded to HF Hub at h200_bundle.tar.gz)
#
# Verification: tar inspection (no keys/, no main_output/, no caches).

set -e

cd "$(dirname "$0")/.."   # repo root

BUNDLE=/tmp/h200_bundle.tar.gz
KEY_FILE=keys/hf_key.txt
REPO_ID=Wuhuwill/main_output
REMOTE_PATH=h200_bundle.tar.gz

if [ ! -f "$KEY_FILE" ]; then
    echo "ERROR: $KEY_FILE missing — cannot authenticate to HF Hub"
    exit 1
fi

# Sanity: rare anchor files must exist (generated by select_anchors_v2.py)
for n in 5 25 75 100; do
    f="data/external_eval/anchors_rare_top${n}.json"
    if [ ! -f "$f" ]; then
        echo "ERROR: $f missing. Run:"
        echo "  conda run -n genfragility python scripts/external_eval/select_anchors_v2.py \\"
        echo "      --n-values 5 25 75 100 --seed 42 --include-rare"
        exit 1
    fi
done

echo "[1/3] Packing bundle -> $BUNDLE"
tar czf "$BUNDLE" \
    --exclude='*.cache*' \
    --exclude='__pycache__' \
    results/checkpoints/final.pkl \
    data/ripple_eval/experiments_final_45 \
    data/external_eval/anchors_hub_top5.json \
    data/external_eval/anchors_hub_top25.json \
    data/external_eval/anchors_hub_top75.json \
    data/external_eval/anchors_hub_top100.json \
    data/external_eval/anchors_random_non_hub_5_seed42.json \
    data/external_eval/anchors_random_non_hub_25_seed42.json \
    data/external_eval/anchors_random_non_hub_75_seed42.json \
    data/external_eval/anchors_random_non_hub_100_seed42.json \
    data/external_eval/anchors_none.json \
    data/external_eval/anchors_rare_top5.json \
    data/external_eval/anchors_rare_top25.json \
    data/external_eval/anchors_rare_top75.json \
    data/external_eval/anchors_rare_top100.json

echo "      bundle size: $(du -h $BUNDLE | cut -f1)"

echo ""
echo "[2/3] Verifying no secrets leaked into bundle ..."
if tar tzf "$BUNDLE" | grep -iE '(key|secret|token|\.env)' >/dev/null; then
    echo "ERROR: bundle contains potentially sensitive files:"
    tar tzf "$BUNDLE" | grep -iE '(key|secret|token|\.env)'
    exit 1
fi
echo "      OK — no key/secret/token files in bundle"

echo ""
echo "[3/3] Uploading to $REPO_ID:$REMOTE_PATH ..."
HF_TOKEN=$(cat "$KEY_FILE")
python3 - <<PY
import os
from huggingface_hub import HfApi
api = HfApi(token=os.environ.get("HF_TOKEN") or "$HF_TOKEN")
api.upload_file(
    path_or_fileobj="$BUNDLE",
    path_in_repo="$REMOTE_PATH",
    repo_id="$REPO_ID",
    repo_type="model",
    commit_message="Upload H200 data bundle (graph + targets + anchors incl. rare)",
)
print("uploaded:", "$REMOTE_PATH")
PY

echo ""
echo "✅ Bundle uploaded to https://huggingface.co/$REPO_ID/blob/main/$REMOTE_PATH"
